# Generated by Django 3.2.6 on 2021-09-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='creation_date',
            field=models.DateField(auto_now=True, verbose_name='Creation Date'),
        ),
        migrations.AddField(
            model_name='book',
            name='creation_date',
            field=models.DateField(auto_now=True, verbose_name='Creation Date'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='author_id',
        ),
        migrations.AddField(
            model_name='book',
            name='author_id',
            field=models.ManyToManyField(to='book.Author'),
        ),
    ]
