# Generated by Django 3.2.6 on 2021-09-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20210904_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='state',
            field=models.BooleanField(default=True, verbose_name='State'),
        ),
    ]
